apiVersion: v1
kind: ConfigMap
metadata:
  name: service-ca-bundle
  annotations:
    include.release.openshift.io/self-managed-high-availability: "true"
    release.openshift.io/create-only: "true"
    service.beta.openshift.io/inject-cabundle: "true"
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/single-node-developer: "true"
