apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  name: insights-operator
  namespace: openshift-insights
spec:
  description: An operator for gathering information for Insights.
  displayName: Insights Operator
  keywords:
  - insights
  install:
    strategy: deployment
    spec:
      deployments:
      - name: insights-operator
        template:
          selector:
            matchLabels:
              app: insights-operator
          strategy:
            type: Recreate
          template:
            metadata:
              labels:
                app: insights-operator
            spec:
              containers:
              - args:
                - start
                - -v=4
                - --config=/etc/insights-operator/server.yaml
                env:
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: POD_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
                - name: RELEASE_VERSION
                  value: 0.0.1-snapshot
                image: quay.io/openshift/origin-insights-operator:latest
                name: insights-operator
                ports:
                - containerPort: 8443
                  name: https
                resources:
                  requests:
                    cpu: 10m
                    memory: 30Mi
                terminationMessagePolicy: FallbackToLogsOnError
                volumeMounts:
                - mountPath: /var/lib/insights-operator
                  name: snapshots
                - mountPath: /var/run/configmaps/trusted-ca-bundle
                  name: trusted-ca-bundle
                  readOnly: true
                - mountPath: /var/run/configmaps/service-ca-bundle
                  name: service-ca-bundle
                  readOnly: true
                - mountPath: /var/run/secrets/serving-cert
                  name: serving-cert
              nodeSelector:
                beta.kubernetes.io/os: linux
                node-role.kubernetes.io/master: ""
              priorityClassName: system-cluster-critical
              serviceAccountName: operator
              tolerations:
              - effect: NoSchedule
                key: node-role.kubernetes.io/master
                operator: Exists
              - effect: NoExecute
                key: node.kubernetes.io/unreachable
                operator: Exists
                tolerationSeconds: 900
              - effect: NoExecute
                key: node.kubernetes.io/not-ready
                operator: Exists
                tolerationSeconds: 900
              volumes:
              - emptyDir: {}
                name: snapshots
              - configMap:
                  name: trusted-ca-bundle
                  optional: true
                name: trusted-ca-bundle
              - configMap:
                  name: service-ca-bundle
                  optional: true
                name: service-ca-bundle
              - name: serving-cert
                secret:
                  optional: true
                  secretName: openshift-insights-serving-cert
    customresourcedefinitions:
      owned: []
      required: []
    nativeAPIs: #TODO add more here
    - group: ""
      version: v1
      kind: Pod
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: false
    type: AllNamespaces