apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: support.config.openshift.io
spec:
  group: config.openshift.io
  versions:
  - name: v1
    served: true
    storage: true
  scope: Cluster
  subresources:
    status: {}
  names:
    plural: support
    singular: support
    kind: Support
  additionalPrinterColumns:
  - name: Report
    type: string
    JSONPath: .spec.reportHealth
