kind: GenericOperatorConfig
apiVersion: operator.openshift.io/v1alpha1
leaderElection:
  disable: true
interval: "30s"
storagePath: /tmp/support-operator
endpoint: http://localhost:8081
impersonate: system:serviceaccount:openshift-support:gather