kind: GenericOperatorConfig
apiVersion: operator.openshift.io/v1alpha1
leaderElection:
  disable: true
interval: "5m"
storagePath: /tmp/insights-operator
endpoint: http://[::1]:8081
impersonate: system:serviceaccount:openshift-insights:gather
gather:
  - pdbs
  - metrics
  - operators
  - container_images
  - nodes
  - config_maps
  - version
  - id
  - infrastructure
  - network
  - authentication
  - image_registry
  - image_pruner
  - feature_gates
  - oauth
  - ingress
  - proxy
  - certificate_signing_requests
  - crd
  - host_subnet
  - machine_set
  - install_plans
  - service_accounts
  - machine_config_pool
  - container_runtime_config
#  - stateful_sets
