kind: GenericOperatorConfig
apiVersion: operator.openshift.io/v1alpha1
leaderElection:
  disable: true
interval: "2h"
storagePath: /var/lib/insights-operator
endpoint: https://cloud.redhat.com/api/ingress/v1/upload
impersonate: system:serviceaccount:openshift-insights:gather
pull_report:
  endpoint: https://cloud.redhat.com/api/insights-results-aggregator/v1/clusters/%s/report
  delay: "60s"
  timeout: "3000s"
  min_retry: "30s"
gather:
  - pdbs
  - metrics
  - operators
  - container_images
  - nodes
  - config_maps
  - version
  - id
  - infrastructure
  - network
  - authentication
  - image_registry
  - image_pruner
  - feature_gates
  - oauth
  - ingress
  - proxy
  - certificate_signing_requests
  - crd
  - host_subnet
  - machine_set
  - install_plans
  - service_accounts
  - machine_config_pool
  - container_runtime_config
  - stateful_sets